"""security_and_contracts

Revision ID: 9bc026dc6e3a
Revises: 2b9d4ba2c45d
Create Date: 2026-08-30 17:46:48.298815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc026dc6e3a'
down_revision: Union[str, Sequence[str], None] = '2b9d4ba2c45d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_codes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code_digest', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promo_codes_code_digest'), ['code_digest'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_payment_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_provider_payment_id'), ['provider_payment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('workspace_memberships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_memberships_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_memberships_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('project_access_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('ttl', sa.String(), nullable=True),
    sa.Column('single_use', sa.Boolean(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=True),
    sa.Column('activated_fingerprint', sa.String(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_access_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_access_links_token_hash'), ['token_hash'], unique=True)

    op.create_table('tunnel_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tunnel_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('connect_token_digest', sa.String(), nullable=False),
    sa.Column('target_port', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tunnel_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tunnel_sessions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tunnel_sessions_tunnel_id'), ['tunnel_id'], unique=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_token_digest', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('custom_boards', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ticket_seq', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('revision', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('telemetry_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ai_data_sharing', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('public_widget_key_digest', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('public_widget_origins', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('github_repo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('github_token_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('github_sync_enabled', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_projects_api_token_digest'), ['api_token_digest'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_public_widget_key_digest'), ['public_widget_key_digest'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('api_token')

    with op.batch_alter_table('spec_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('github_issue_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('github_issue_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('revision', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_spec_tickets_key'), ['key'], unique=False)

    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('billing_provider', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('company_inn', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_lifetime_free', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('promo_code_used', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payment_method_refused', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('payment_method_refused_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_workspaces_api_key', ['api_key'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_constraint('uq_workspaces_api_key', type_='unique')
        batch_op.drop_column('payment_method_refused_at')
        batch_op.drop_column('payment_method_refused')
        batch_op.drop_column('promo_code_used')
        batch_op.drop_column('is_lifetime_free')
        batch_op.drop_column('company_name')
        batch_op.drop_column('company_inn')
        batch_op.drop_column('billing_provider')
        batch_op.drop_column('api_key')

    with op.batch_alter_table('spec_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spec_tickets_key'))
        batch_op.drop_column('revision')
        batch_op.drop_column('github_issue_number')
        batch_op.drop_column('github_issue_url')
        batch_op.drop_column('key')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_token', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_projects_public_widget_key_digest'))
        batch_op.drop_index(batch_op.f('ix_projects_api_token_digest'))
        batch_op.drop_column('github_sync_enabled')
        batch_op.drop_column('github_token_encrypted')
        batch_op.drop_column('github_repo')
        batch_op.drop_column('public_widget_origins')
        batch_op.drop_column('public_widget_key_digest')
        batch_op.drop_column('ai_data_sharing')
        batch_op.drop_column('telemetry_enabled')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('revision')
        batch_op.drop_column('ticket_seq')
        batch_op.drop_column('custom_boards')
        batch_op.drop_column('api_token_digest')

    with op.batch_alter_table('tunnel_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tunnel_sessions_tunnel_id'))
        batch_op.drop_index(batch_op.f('ix_tunnel_sessions_project_id'))

    op.drop_table('tunnel_sessions')
    with op.batch_alter_table('project_access_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_access_links_token_hash'))

    op.drop_table('project_access_links')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))

    op.drop_table('audit_events')
    with op.batch_alter_table('workspace_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_memberships_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_memberships_user_id'))

    op.drop_table('workspace_memberships')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_token'))

    op.drop_table('sessions')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_payments_provider_payment_id'))

    op.drop_table('payments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promo_codes_code_digest'))

    op.drop_table('promo_codes')
    # ### end Alembic commands ###
